# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  workflow_dispatch:
  
  push:
    branches: [ master ]
    paths:
      - '**.js'
      - '**.sh'

  pull_request:
    branches: [ master ]
    paths:
      - '**.js'
      - '**.sh'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      max-parallel: 3
      matrix:
        os: [macos-latest, windows-latest, ubuntu-18.04]
        node-version: [10.x ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd sandbox/
    - run: npm ci
    - run: npm run enable-link --if-present
    - run: npm run chain --if-present
    - run: npm run chain-integration --if-present
    - run: npm test
